import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

function formatCWSystemsEmail(orderData: any, isTest: boolean): { subject: string; html: string } {
  const items = orderData.items || [];
  const subject = `${isTest ? '[TEST] ' : ''}Purchase Order from ${orderData.accountName} (${orderData.accountCode})`;

  const itemRows = items.map((item: any, idx: number) => `
    <tr style="border-bottom: 1px solid #e5e7eb;">
      <td style="padding: 8px; text-align: center;">${idx + 1}</td>
      <td style="padding: 8px;">${item.code || '-'}</td>
      <td style="padding: 8px;">${item.description || '-'}</td>
      <td style="padding: 8px; text-align: center;">${item.quantity || 1}</td>
      <td style="padding: 8px;">${item.width || '-'} x ${item.drop || item.height || '-'}</td>
      <td style="padding: 8px;">${item.color || '-'}</td>
      <td style="padding: 8px;">${item.notes || ''}</td>
    </tr>
  `).join('');

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      ${isTest ? '<div style="background: #fef3c7; border: 2px solid #f59e0b; padding: 12px; margin-bottom: 20px; border-radius: 6px; text-align: center; font-weight: bold; color: #92400e;">TEST ORDER - PLEASE IGNORE</div>' : ''}

      <h2 style="color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 8px;">
        Purchase Order — CW Systems
      </h2>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 20px 0;">
        <div>
          <p><strong>Account Code:</strong> ${orderData.accountCode || '-'}</p>
          <p><strong>Account Name:</strong> ${orderData.accountName || '-'}</p>
          <p><strong>Contact:</strong> ${orderData.contactName || '-'}</p>
          <p><strong>Phone:</strong> ${orderData.contactPhone || '-'}</p>
        </div>
        <div>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-AU', { day: '2-digit', month: '2-digit', year: 'numeric' })}</p>
          <p><strong>Payment Terms:</strong> ${orderData.paymentTerms || 'Account 30 Days'}</p>
          <p><strong>PO Number:</strong> ${orderData.poNumber || 'TBC'}</p>
        </div>
      </div>

      <div style="margin: 20px 0;">
        <p><strong>Delivery Address:</strong></p>
        <p style="white-space: pre-line; color: #4b5563;">${orderData.deliveryAddress || 'Not specified'}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; border: 1px solid #e5e7eb; margin: 20px 0;">
        <thead>
          <tr style="background: #f3f4f6;">
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #d1d5db;">#</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Item Code</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Description</th>
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #d1d5db;">Qty</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">W x D</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Colour</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Notes</th>
          </tr>
        </thead>
        <tbody>
          ${itemRows}
        </tbody>
      </table>

      ${orderData.notes ? `
        <div style="margin: 20px 0; padding: 12px; background: #f9fafb; border-radius: 6px;">
          <p style="margin: 0;"><strong>Order Notes:</strong></p>
          <p style="margin: 4px 0 0; color: #4b5563; white-space: pre-line;">${orderData.notes}</p>
        </div>
      ` : ''}

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px;">
        <p>This order was generated by InterioApp. Please confirm receipt.</p>
      </div>
    </div>
  `;

  return { subject, html };
}

function formatNormanEmail(orderData: any, isTest: boolean): { subject: string; html: string } {
  const items = orderData.items || [];
  const subject = `${isTest ? '[TEST] ' : ''}Purchase Order from ${orderData.accountName} (Acc: ${orderData.accountNumber})`;

  const itemRows = items.map((item: any, idx: number) => `
    <tr style="border-bottom: 1px solid #e5e7eb;">
      <td style="padding: 8px; text-align: center;">${idx + 1}</td>
      <td style="padding: 8px;">${item.code || '-'}</td>
      <td style="padding: 8px;">${item.description || '-'}</td>
      <td style="padding: 8px; text-align: center;">${item.quantity || 1}</td>
      <td style="padding: 8px;">${item.width || '-'} x ${item.height || item.drop || '-'}</td>
      <td style="padding: 8px;">${item.color || '-'}</td>
      <td style="padding: 8px;">${item.notes || ''}</td>
    </tr>
  `).join('');

  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px;">
      ${isTest ? '<div style="background: #fef3c7; border: 2px solid #f59e0b; padding: 12px; margin-bottom: 20px; border-radius: 6px; text-align: center; font-weight: bold; color: #92400e;">TEST ORDER - PLEASE IGNORE</div>' : ''}

      <h2 style="color: #1f2937; border-bottom: 2px solid #059669; padding-bottom: 8px;">
        Purchase Order — Norman Australia
      </h2>

      <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 20px 0;">
        <div>
          <p><strong>Account Number:</strong> ${orderData.accountNumber || '-'}</p>
          <p><strong>Account Name:</strong> ${orderData.accountName || '-'}</p>
          <p><strong>Contact:</strong> ${orderData.contactName || '-'}</p>
          <p><strong>Phone:</strong> ${orderData.contactPhone || '-'}</p>
        </div>
        <div>
          <p><strong>Date:</strong> ${new Date().toLocaleDateString('en-AU', { day: '2-digit', month: '2-digit', year: 'numeric' })}</p>
          <p><strong>Payment Terms:</strong> ${orderData.paymentTerms || 'Account 30 Days'}</p>
          <p><strong>PO Number:</strong> ${orderData.poNumber || 'TBC'}</p>
          <p><strong>Job Reference:</strong> ${orderData.jobReference || '-'}</p>
        </div>
      </div>

      <div style="margin: 20px 0;">
        <p><strong>Delivery Address:</strong></p>
        <p style="white-space: pre-line; color: #4b5563;">${orderData.deliveryAddress || 'Not specified'}</p>
      </div>

      <table style="width: 100%; border-collapse: collapse; border: 1px solid #e5e7eb; margin: 20px 0;">
        <thead>
          <tr style="background: #f3f4f6;">
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #d1d5db;">#</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Item Code</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Description</th>
            <th style="padding: 10px; text-align: center; border-bottom: 2px solid #d1d5db;">Qty</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">W x H</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Colour</th>
            <th style="padding: 10px; text-align: left; border-bottom: 2px solid #d1d5db;">Notes</th>
          </tr>
        </thead>
        <tbody>
          ${itemRows}
        </tbody>
      </table>

      ${orderData.notes ? `
        <div style="margin: 20px 0; padding: 12px; background: #f9fafb; border-radius: 6px;">
          <p style="margin: 0;"><strong>Order Notes:</strong></p>
          <p style="margin: 4px 0 0; color: #4b5563; white-space: pre-line;">${orderData.notes}</p>
        </div>
      ` : ''}

      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px;">
        <p>This order was generated by InterioApp. Please confirm receipt.</p>
      </div>
    </div>
  `;

  return { subject, html };
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("No authorization header");

    const token = authHeader.replace("Bearer ", "");
    const { data: { user }, error: userError } = await supabase.auth.getUser(token);
    if (userError || !user) throw new Error("Unauthorized");

    const { supplier, orderData, test, projectId } = await req.json();

    if (!supplier || !orderData) {
      throw new Error("Missing supplier or orderData");
    }

    // Format email based on supplier
    let emailContent: { subject: string; html: string };

    switch (supplier) {
      case 'cw_systems':
        emailContent = formatCWSystemsEmail(orderData, !!test);
        break;
      case 'norman_australia':
        emailContent = formatNormanEmail(orderData, !!test);
        break;
      default:
        throw new Error(`Unknown supplier: ${supplier}`);
    }

    const recipientEmail = orderData.supplierEmail;
    if (!recipientEmail) {
      throw new Error("Missing supplier email address");
    }

    // Send via the existing send-email edge function
    const { error: sendError } = await supabase.functions.invoke('send-email', {
      body: {
        to: recipientEmail,
        subject: emailContent.subject,
        html: emailContent.html,
        replyTo: user.email,
        userId: user.id,
      },
    });

    if (sendError) {
      console.error('Failed to send supplier order email:', sendError);
      throw new Error(`Failed to send email: ${sendError.message}`);
    }

    // Send a copy to the user
    if (user.email) {
      await supabase.functions.invoke('send-email', {
        body: {
          to: user.email,
          subject: `[Copy] ${emailContent.subject}`,
          html: `<p style="color: #6b7280; font-size: 14px; margin-bottom: 16px;">This is your copy of the order submitted to <strong>${recipientEmail}</strong>.</p>${emailContent.html}`,
          userId: user.id,
        },
      });
    }

    // Record the order submission
    if (projectId) {
      const { data: project } = await supabase
        .from('projects')
        .select('supplier_orders')
        .eq('id', projectId)
        .single();

      const existingOrders = (project as any)?.supplier_orders || {};
      existingOrders[supplier] = {
        status: 'email_sent',
        submitted_at: new Date().toISOString(),
        submitted_method: 'email',
        supplier_email: recipientEmail,
        is_test: !!test,
      };

      await supabase
        .from('projects')
        .update({ supplier_orders: existingOrders } as any)
        .eq('id', projectId);
    }

    console.log(`Supplier order email sent to ${recipientEmail} for ${supplier}${test ? ' (TEST)' : ''}`);

    return new Response(
      JSON.stringify({ success: true, message: `Order email sent to ${recipientEmail}` }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: any) {
    console.error("Supplier order email error:", error);
    return new Response(
      JSON.stringify({ error: error.message || "Failed to send supplier order" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
